version: '3'

services: 

  app:
    build:
      context: node
    container_name: app

    networks:
      - mynet
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s 
                docker-entrypoint.sh
                node index.js
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx-node
      dockerfile: Dockerfile.prod
    image: nginx-node:prod
    container_name: nginx-node
    networks: 
      - mynet
    ports: 
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet
  
networks: 
  mynet:
    driver: bridge

